### ISSUE TITLE
Would you please provide an script to switch java.

### ISSUE THREAD

**Issue by liaoya** [se35710/scoop-java#1]
I like scoop and your java bucket. It has a little inconvenience that
- It always add bin to PATH so that there will be multi java in path even first one will win
- It will reset `JAVA_HOME` when the new java installed

I will switch to different java frequently. It's perfect if 
- Do not put bin in `PATH` when new java installed
- Provide a script to switch java by reset JAVA_HOME, remove old `%JAVA_HOME%\bin` from `PATH` and add the new one.

**Comment by se35710** [comment]
There are two solutions available today, without removing `env_add_path` from the manifests:

1. `scoop reset <java>@<version>`
2. Using [find-java](https://github.com/lukesampson/scoop-extras/blob/master/find-java.json) from [extras](https://github.com/lukesampson/scoop-extras)

`scoop reset` works very well for the current session, and will also update the user's path.

Globally installed javas takes precedence over user installed javas, so if you have admin rights on your PC, `scoop install -g oraclejdk-lts` will install a java that is always default for new sessions.

Consider the following:
```
PS C:> scoop install oraclejdk-lts
Installing 'oraclejdk-lts' (8u172-b11) [64bit]
PS C:> scoop install oraclejdk10
Installing 'oraclejdk10' (10.0.1-10) [64bit]
PS C:> scoop install zulu6
Installing 'zulu6' (6.18.1.5) [64bit]
PS C:> scoop install openjdk10
Installing 'openjdk10' (10.0.1) [64bit]
PS C:> java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)
PS C:> scoop reset zulu6
Resetting zulu6 (6.18.1.5).
Linking ~\scoop\apps\zulu6\current => ~\scoop\apps\zulu6\6.18.1.5
PS C:> java -version
openjdk version "1.6.0-99"
OpenJDK Runtime Environment (Zulu 6.18.1.5-win64) (build 1.6.0-99-b99)
OpenJDK 64-Bit Server VM (Zulu 6.18.1.5-win64) (build 23.77-b99, mixed mode)
PS C:> scoop reset oraclejdk-lts
PS C:> java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```
Hope that helps!
