### ISSUE TITLE
adopt8-openj9@8u181-b13_164: hash check failed

### ISSUE THREAD

**Issue by kaveman-** [se35710/scoop-java#14]
Checking hash of OpenJDK8_x64_Windows_201808291330.zip ... ERROR Hash check failed!
App:         java/adopt8-openj9
URL:         https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_windows/164/artifact/OpenJDK8_x64_Windows_201808291330.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    e2b8537fc54ad662dcd3e95bb6a94bab9c3fa4a63fe425ffabd495df008fe63e
Actual:      e1f3d4a8e8a61edc063e77ce485659cfd1809fd2a36c78b9f708c788b5db5d29

**Comment by se35710** [comment]
Fixed with commit [53fd1de](https://github.com/se35710/scoop-java/commit/53fd1de0f9c38b8c852206764cace79489a51e05).

**Comment by kaveman-** [comment]
now I get this:

Checking hash of OpenJDK8_x64_Windows_201808301330.zip ... ERROR Hash check failed!
App:         java/adopt8-openj9
URL:         https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_windows/165/artifact/OpenJDK8_x64_Windows_201808301330.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    174adef6191b511971d551d062431d0f
Actual:      52070f0ff4e45629558aae90e289dab4

**Comment by se35710** [comment]
Their CI environment is not producing the MD5 hashes quickly enough after they have published their builds. It should extract the MD5 correctly now, and fallback to downloading if it fails.

I have also added all the AdoptOpenJDK manifests as snowflakes to `auto-pr.ps1`, so hopefully if the hash changes it will be committed during the normal update checks (about every 15 minutes or so).
