### ISSUE TITLE
fatal: refusing to merge unrelated histories

### ISSUE THREAD

**Issue by se35710** [se35710/scoop-java#16]
Resolve by removing and adding the java bucket again:

```
PS C:> scoop bucket rm java
PS C:> scoop bucket add java
```
Related issue in scoop: [#2566](https://github.com/lukesampson/scoop/issues/2566).

**Comment by se35710** [comment]
@derkoe, @minorgod, @plombard, @raikesy You all have forks of the old master. Please remove the fork and if you want fork again from the new master. You will also have to clone again from the new fork. Sorry for the inconvenience.

**Comment by plombard** [comment]
Okay, deleted it (I no longer need it). Thanks for the heads up.

**Comment by BjoernPetersen** [comment]
Please make the master branch protected (Settings -> Branches -> Add Rule -> Apply to "master" and Check the "Include administrators" box) to prevent this happening again.

**Comment by se35710** [comment]
@BjoernPetersen Added that now, thanks!
