### ISSUE TITLE
Please consider adding oraclejre which always installs latest version (now 10.x)

### ISSUE THREAD

**Issue by mstevens83** [se35710/scoop-java#23]
Title says it all.

Version-agnostic "oraclejre" and "oraclejre-server" entries are fact already assumed to exist here on the [Scoop Java Wiki page](https://github.com/lukesampson/scoop/wiki/Java), but the links are dead. I reported this here: https://github.com/lukesampson/scoop/issues/2622

**Comment by se35710** [comment]
(Server-)JRE are not part of Oracle's Java any more.
