### ISSUE TITLE
adopt11-hotspot@11-28: hash check failed

### ISSUE THREAD

**Issue by Findulas** [se35710/scoop-java#27]
ERROR Hash check failed!
App:         java/adopt11-hotspot
URL:         https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11%2B28/OpenJDK11-jdk_x64_windows_hotspot_11_28.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    311466765ef02a0a3450571417a63f72f515f00c6cd66cee7fcf630c03374e47
Actual:      11a31d269c6527e9ba2e97cd502869fc130ef206ca5f55cccc0fa825401eb44d

The expected hash according to the adopt Website is 11a31d269c6527e9ba2e97cd502869fc130ef206ca5f55cccc0fa825401eb44d  target/windows/x64/hotspot/OpenJDK11-jdk_x64_windows_hotspot_11_28.zip

**Comment by se35710** [comment]
Should be fixed now.

**Comment by Findulas** [comment]
Fix confirmed.
