### ISSUE TITLE
oraclejdk-lts@11.0.2-9: hash check failed

### ISSUE THREAD

**Issue by ntt2k** [se35710/scoop-java#36]
Checking hash of jdk-11.0.2_windows-x64_bin.zip ... ERROR Hash check failed!
App:         java/oraclejdk-lts
URL:         http://download.oracle.com/otn-pub/java/jdk/11.0.2+9/f51449fcd52f4d52b93a989c5c56ed3c/jdk-11.0.2_windows-x64_bin.zip
First bytes: 3C 68 74 6D 6C 3E 0D 0A
Expected:    f38976b64633920ed27821fbd80ca924ce55d51b88f4de1933cacc8beecc5a60
Actual:      80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd

**Comment by se35710** [comment]
I think something happened during the download. The expected hash is the real hash, see here: https://www.oracle.com/webfolder/s/digest/11-0-2-checksum.html

run `scoop cache rm oraclejdk-lts` and try again.

**Comment by se35710** [comment]
https://github.com/lukesampson/scoop/issues/3250 might be related
