### ISSUE TITLE
oraclejdk8u@8u202-b08: hash check failed

### ISSUE THREAD

**Issue by ClefZz** [se35710/scoop-java#38]
Tried to `scoop update oraclejdk8u` via and got the following error:

```
ERROR Hash check failed!
App:         java/oraclejdk8u
URL:         http://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-windows-x64.exe#/dl.7z
First bytes: 3C 68 74 6D 6C 3E 0D 0A
Expected:    b3bcdd6007e30c7b9d459b5bef766ac49f1e0b1cc92b11b19af3cf0439c3bc9f
Actual:      80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd
```

I have checked and found it seems caused by unauthorized request. To workaround, certain cookie has to be attached to the request. More details can be found [here](https://stackoverflow.com/questions/10268583/downloading-java-jdk-on-linux-via-wget-is-shown-license-page-instead).

However I failed to find a way to apply that in scoop. Is there any solution or workaround?

Thanks a lot!

**Comment by h404bi** [comment]
It has cookie attached in the manifest, and the hash is correct. Please cleanup the cache try it again.
https://github.com/se35710/scoop-java/blob/2e24eb6dc1d99c70a31efaa0757c4b4a2fc3c235/bucket/oraclejdk8u.json#L16-L18

**Comment by ClefZz** [comment]
I tried the update again and captured the request by Fiddler and found no cookies. Then I uninstalled the package and reinstalled it and then succeeded -- the cookie now presents in the request.

So I guess it's caused by scoop itself. I am going to check it.

Anyway, thanks a lot!
