### ISSUE TITLE
oraclejdk@12-33: hash check failed

### ISSUE THREAD

**Issue by mikecarr** [se35710/scoop-java#42]
Updating 'oraclejdk' (11.0.2-9 -> 12-33)
Downloading new version
Downloading https://download.oracle.com/otn-pub/java/jdk/12+33/312335d836a34c7c8bba9d963e26dc23/jdk-12_windows-x64_bin.zip (5.2 KB)...
Checking hash of jdk-12_windows-x64_bin.zip ... ERROR Hash check failed!
App:         java/oraclejdk
URL:         https://download.oracle.com/otn-pub/java/jdk/12+33/312335d836a34c7c8bba9d963e26dc23/jdk-12_windows-x64_bin.zip
First bytes: 3C 68 74 6D 6C 3E 0D 0A
Expected:    e79abe2b5620aa01f051c9718ba6806f8882883eef8569e87a44fc2feed36d40
Actual:      80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/se35710/scoop-java/issues/new?title=oraclejdk%4012-33%3a+hash+check+failed

**Comment by se35710** [comment]
Please see issue https://github.com/lukesampson/scoop/issues/3250

Quickfix is to uninstall and then install oraclejdk again.
