### ISSUE TITLE
ojdkbuild8 missing openjfx & webstart

### ISSUE THREAD

**Issue by bernstein82** [se35710/scoop-java#44]
as described on [ojdkbuild wiki](https://github.com/ojdkbuild/ojdkbuild/wiki/Motivation#windows-builds) the zip does not include openjfx & webstart, but the msi does contain them.

i don't know if this was an intentional choice but i'd request the manifest be changed to the msi version for improved compatibility.

**Comment by se35710** [comment]
Any naming suggestions for the new manifest?

**Comment by bernstein82** [comment]
thanks, couldn't have come up with better naming
