### ISSUE TITLE
Why did you remove oraclejdk11?

### ISSUE THREAD

**Issue by astappiev** [se35710/scoop-java#50]
Oracle JDK 11 is an LTS version and I think it should be available. At least I will continue to use it and it is very bad that it is not available via scoop anymore.

**Comment by se35710** [comment]
Oracle does not provide LTS version to the public anymore. If you need LTS, you have to use AdoptOpenJDK, ojdkbuild, Zulu or Corretto.

**Comment by aaaweisen** [comment]
Third party download address
