### ISSUE TITLE
oracle jdk url is no longer valid

### ISSUE THREAD

**Issue by iharh** [se35710/scoop-java#7]
The remote server returned an error: (302) Moved Temporarily.
URL http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jdk-8u171-windows-x64.exe#/dl.7z is not valid

**Comment by se35710** [comment]
I have no issues installing Oracle 8 JDK:

```
C:> scoop install oraclejdk8
Installing 'oraclejdk8' (8u171-b11) [64bit]
jdk-8u171-windows-x64.exe (207,3 MB) [========================================================================] 100%
Checking hash of jdk-8u171-windows-x64.exe... ok.
Extracting... done.
Running pre-install script...
Linking ~\scoop\apps\oraclejdk8\current => ~\scoop\apps\oraclejdk8\8u171-b11
'oraclejdk8' (8u171-b11) was installed successfully!
```

Can you run a `scoop status` and a `scoop checkup` and provide the output?

**Comment by iharh** [comment]
PS C:\Users\Ihar_Hancharenka> scoop status
Scoop is up to date.
Everything is ok!
PS C:\Users\Ihar_Hancharenka> scoop checkup
No problems identified!

**Comment by se35710** [comment]
Seems to be related to issue [913](https://github.com/lukesampson/scoop-extras/issues/913) in [scoop-extras](https://github.com/lukesampson/scoop-extras). I would ask on [Gitter](https://gitter.im/lukesampson/scoop), or create an issue in [scoop](https://github.com/lukesampson/scoop) and then reference this issue. The manifest itself works (see above), but for some reason scoop is unable to follow the redirects in some cases.

**Comment by iharh** [comment]
Frankly speaking, few weeks ago I was able to install Oracle JDK at Win 8 (or 8.1). But after the mandatory upgrade to Win 10 - that does not work anymore.

**Comment by iharh** [comment]
I decided to stay with zulu8 for now

**Comment by se35710** [comment]
@iharh @raikesy You can create an issue in [scoop](https://github.com/lukesampson/scoop), mentioning this issue and [the one](https://github.com/lukesampson/scoop-extras/issues/913) in scoop-extras.

**Comment by se35710** [comment]
With the new aria2 download support introduced in PR [#2312](https://github.com/lukesampson/scoop/pull/2312) you should be able to download and install oraclejdk. Just make sure you have [aria2](https://github.com/lukesampson/scoop/blob/master/bucket/aria2.json) installed.
