### ISSUE TITLE
Latest oraclejre update fail

### ISSUE THREAD

**Issue by Ash258** [se35710/scoop-java#8]
```
Installing 'oraclejre' (10.0.2-13) [64bit]
The remote server returned an error: (302) Moved Temporarily.
URL http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jre-10.0.2_windows-x64_bin.tar.gz is not valid
```

**Comment by Ash258** [comment]
Same for JDK

**Comment by se35710** [comment]
Seems to be related to issue #7 

Could you open an issue at [scoop](
https://github.com/lukesampson/scoop), since this is not a manifest error.

**Comment by se35710** [comment]
With the new aria2 download support introduced in PR [#2312](https://github.com/lukesampson/scoop/pull/2312) you should be able to download and install oraclejdk. Just make sure you have [aria2](https://github.com/lukesampson/scoop/blob/master/bucket/aria2.json) installed.
